# Começando a trabalhar com o NumPy

In [1]:
import numpy as np

Vamos criar a matriz $$ \begin{pmatrix} 1,0 & 4,0 & 0,0 \end{pmatrix} $$

In [2]:
a = np.array([1, 4, 0], float)


In [3]:
a

array([1., 4., 0.])

In [4]:
b = np.array([5.2, 3.7, 2])

In [5]:
b

array([5.2, 3.7, 2. ])

In [6]:
soma = a + b

In [7]:
soma

array([6.2, 7.7, 2. ])

In [8]:
diferenca = a - b

In [9]:
a - b

array([-4.2,  0.3, -2. ])

In [10]:
elementoXelemento = a * b

In [11]:
elementoXelemento

array([ 5.2, 14.8,  0. ])

In [12]:
constanteXmatriz = -5.7 * b

In [13]:
constanteXmatriz

array([-29.64, -21.09, -11.4 ])

In [14]:
for i in b:
       print(-5.7 * i)

-29.64
-21.090000000000003
-11.4


In [15]:
for i in range(3):
       print (b[i])

5.2
3.7
2.0


In [16]:
range(3)

range(0, 3)

In [17]:
range(5,11,2)

range(5, 11, 2)

In [18]:
range(5,12,2)

range(5, 12, 2)

In [19]:
c = np.array([[5.5, 7.8, 8.5] , [7.8 ,1.2, 6.78] , [1., 9., 6.]])

In [20]:
c

array([[5.5 , 7.8 , 8.5 ],
       [7.8 , 1.2 , 6.78],
       [1.  , 9.  , 6.  ]])

In [21]:
d = np.zeros((3, 3), float)

In [22]:
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
d1 = np.zeros((3, 3),float)

In [24]:
e = np.sqrt(np.cos(d))
e


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.sum(e)

9.0

In [26]:
np.prod(e)

1.0

In [27]:
f = c.transpose()

In [28]:
f

array([[5.5 , 7.8 , 1.  ],
       [7.8 , 1.2 , 9.  ],
       [8.5 , 6.78, 6.  ]])

In [29]:
c

array([[5.5 , 7.8 , 8.5 ],
       [7.8 , 1.2 , 6.78],
       [1.  , 9.  , 6.  ]])

In [30]:
np.concatenate((c,f))

array([[5.5 , 7.8 , 8.5 ],
       [7.8 , 1.2 , 6.78],
       [1.  , 9.  , 6.  ],
       [5.5 , 7.8 , 1.  ],
       [7.8 , 1.2 , 9.  ],
       [8.5 , 6.78, 6.  ]])

In [31]:
np.concatenate((c,f),axis=0)

array([[5.5 , 7.8 , 8.5 ],
       [7.8 , 1.2 , 6.78],
       [1.  , 9.  , 6.  ],
       [5.5 , 7.8 , 1.  ],
       [7.8 , 1.2 , 9.  ],
       [8.5 , 6.78, 6.  ]])

In [32]:
np.concatenate((c,f),axis=1)

array([[5.5 , 7.8 , 8.5 , 5.5 , 7.8 , 1.  ],
       [7.8 , 1.2 , 6.78, 7.8 , 1.2 , 9.  ],
       [1.  , 9.  , 6.  , 8.5 , 6.78, 6.  ]])

##### Lembrar que, nas funções trigonométricas, os ângulos devem estar em radianos!

In [39]:
seno_de_trinta_graus = np.sin(np.pi/6)
print('seno de trinta graus = ',seno_de_trinta_graus)

seno de trinta graus =  0.49999999999999994
